@startuml
start
:После запуска приложения данные о расстоянии между точками считывается из файла;
:Генератором случайных чисел участкам дороги задается скорость в диапазоне от 30 км/ч до 80 км/ч;
:Ввод пользователем двух точек;
if ()then (да)
: Рассчет минимальноговремени в пути;
:Вывод информации о средних скоростях на участках;
:Вывод времени в пути;
else (нет)
:Ошибка;
endif
:Завершение работы приложения;
stop
@enduml